name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v1.1.1
      with:
        extra_args: --all-files
